version: '3.8'

services:
  # --- FRONTEND ---
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: mesp-frontend
    ports:
      - "80:80"
    restart: always
    depends_on:
      - backend
    networks:
      - mesp-network

  # --- BACKEND ---
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: mesp-backend
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - mesp-network
    environment:
      - PORT=5000
      - JWT_SECRET=mesp_secret_key_prod
      - NODE_ENV=production
      - MONGO_URI=mongodb://db:27017/mesp_hr_db

  # --- DATABASE ---
  db:
    image: mongo:latest
    container_name: mesp-db
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - mongo-data:/data/db
    networks:
      - mesp-network

networks:
  mesp-network:
    driver: bridge

volumes:
  mongo-data:
